"""Turn a Wavefront `.obj` into a LOVA mesh.

    python apps/model/obj_to_lova.py knight.obj lib/knight.lova knight

Writes the same shape of file `make_models.py` does: vertices in
1024ths of a model unit, triangles with a material and the face's own
unit normal.  The model is centred on its own bounding box and scaled
so its longest side is two units, because `lib/mesh3d.lova` works in
model units and the viewer's camera expects about that size.

What it reads: `v` lines and `f` lines (any of `f 1 2 3`, `f 1/1 2/2
3/3`, `f 1//1 2//2 3//3`), with polygons fanned into triangles, and
`usemtl` to number the materials in the order they first appear.  What
it ignores: normals and texture coordinates in the file -- the normals
are recomputed from the winding, because a face here carries one unit
normal and not three -- and everything else.

Blender writes this format from File > Export > Wavefront (.obj).
Keep the model low: the renderer costs about 220 LOVA steps a triangle,
so 50 triangles runs at 40 frames a second and 300 at 8.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

ONE = 1024


def read_obj(path: Path):
    verts, faces, materials, current = [], [], {}, 0
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        parts = line.split()
        if not parts:
            continue
        if parts[0] == "v":
            verts.append(tuple(float(c) for c in parts[1:4]))
        elif parts[0] == "usemtl":
            current = materials.setdefault(parts[1], len(materials))
        elif parts[0] == "f":
            idx = []
            for token in parts[1:]:
                n = int(token.split("/")[0])
                idx.append(n - 1 if n > 0 else len(verts) + n)
            for k in range(1, len(idx) - 1):          # fan the polygon
                faces.append((idx[0], idx[k], idx[k + 1], current))
    return verts, faces, materials


def fit(verts):
    """Centred on its box, longest side two units."""
    lo = [min(v[k] for v in verts) for k in range(3)]
    hi = [max(v[k] for v in verts) for k in range(3)]
    mid = [(lo[k] + hi[k]) / 2 for k in range(3)]
    span = max(hi[k] - lo[k] for k in range(3)) or 1.0
    return [tuple((v[k] - mid[k]) * 2 / span for k in range(3)) for v in verts]


def normal(verts, face):
    a, b, c = (verts[i] for i in face[:3])
    u = tuple(b[k] - a[k] for k in range(3))
    w = tuple(c[k] - a[k] for k in range(3))
    n = (u[1] * w[2] - u[2] * w[1],
         u[2] * w[0] - u[0] * w[2],
         u[0] * w[1] - u[1] * w[0])
    length = math.sqrt(sum(v * v for v in n)) or 1.0
    return tuple(v / length for v in n)


def main(argv) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2
    src, dst = Path(argv[1]), Path(argv[2])
    name = argv[3] if len(argv) > 3 else src.stem.replace("_", "-")
    verts, faces, materials = read_obj(src)
    if not verts or not faces:
        print(f"{src}: no vertices or no faces")
        return 1
    verts = fit(verts)
    fix = lambda v: int(round(v * ONE))
    out = [f";;; {dst.name}  --  {name}, converted from {src.name}",
           ";;;",
           f";;; {len(verts)} vertices, {len(faces)} triangles, "
           f"{max(1, len(materials))} material(s).  Generated by",
           ";;; `python apps/model/obj_to_lova.py`; do not edit by hand.",
           ";;; Every face carries the unit normal its winding gives it, so",
           ";;; the renderer needs no square root.",
           "",
           '(use "mesh3d")',
           "",
           f"(def {name}-vs []", "  (list"]
    out += [f"    (rec x {fix(x):6d} y {fix(y):6d} z {fix(z):6d})" for x, y, z in verts]
    out[-1] += "))"
    out += ["", f"(def {name}-fs []", "  (list"]
    for a, b, c, mat in faces:
        nx, ny, nz = normal(verts, (a, b, c))
        out.append(f"    (rec a {a:4d} b {b:4d} c {c:4d} "
                   f"nx {fix(nx):6d} ny {fix(ny):6d} nz {fix(nz):6d} k {mat})")
    out[-1] += "))"
    out += ["", f"(def {name} [] (mesh {name}-vs {name}-fs))", ""]
    dst.write_text("\n".join(out), encoding="utf-8")
    print(f"{src.name}: {len(verts)} vertices, {len(faces)} triangles, "
          f"{len(materials) or 1} material(s) -> {dst}")
    if len(faces) > 400:
        print(f"  note: {len(faces)} triangles is about "
              f"{len(faces) * 220 // 1000}k LOVA steps a frame, so roughly "
              f"{1000 // max(1, len(faces) * 220 // 500)} frames a second")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
